<ul>
  <?php foreach ($data as $item): ?>
    <?php if (!is_array($item)) continue; ?>

    <li>
      <?php if (isset($item['prefix'])): ?>
        <?=join(' ', $item['prefix']['data']) ?><?=isset($item['linkname']['data'][0]) ? ':' : '' ?>
      <?php endif; ?>

      <?php if (isset($item['link'])): ?>
        <?php
        $query = http_build_query([
          'lookfor' => addcslashes(urlencode($item['link']['data'][0]), '"'),
          'type' => 'PPN',
        ]);
        ?>
        <a href="<?=$this->url('search-results') ?>?<?=$query ?>"><?=$item['linkname']['data'][0] ?></a>
      <?php else: ?>
        <?=$item['linkname']['data'][0] ?? '' ?>
      <?php endif; ?>

      <?php if ($item['author'] ?? $item['volume'] ?? $item['published'] ?? $item['pages'] ?? ''): ?>
        &ndash;
      <?php endif; ?>

      <?php if (isset($item['author'])): ?>
        <?=$item['author']['data'][0] ?>,
      <?php endif; ?>

      <?php if (isset($item['volume'])): ?>
        <?=$item['volume']['data'][0] ?>,
      <?php endif; ?>

      <?php if (isset($item['published'])): ?>
        <?=$item['published']['data'][0] ?>,
      <?php endif; ?>

      <?php if (isset($item['pages'])): ?>
        <?=$item['pages']['data'][0] ?>
      <?php endif; ?>
    </li>
  <?php endforeach; ?>
</ul>
